class BdGeoData {
  static const List<String> divisions = [
    "Dhaka",
    "Chittagong",
    "Rajshahi",
    "Khulna",
    "Barisal",
    "Sylhet",
    "Rangpur",
    "Mymensingh",
  ];

  static const Map<String, List<String>> districts = {
    "Dhaka": [
      "Dhaka",
      "Gazipur",
      "Narayanganj",
      "Tangail",
      "Manikganj",
      "Munshiganj",
      "Narsingdi",
      "Kishoreganj",
      "Faridpur",
      "Gopalganj",
      "Madaripur",
      "Rajbari",
      "Shariatpur",
    ],
    "Chittagong": [
      "Chittagong",
      "Cox's Bazar",
      "Comilla",
      "Feni",
      "Lakshmipur",
      "Noakhali",
      "Chandpur",
      "Brahmanbaria",
      "Rangamati",
      "Khagrachhari",
      "Bandarban",
    ],
    "Rajshahi": [
      "Rajshahi",
      "Naogaon",
      "Natore",
      "Nawabganj",
      "Pabna",
      "Bogra",
      "Sirajganj",
      "Joypurhat",
    ],
    "Khulna": [
      "Khulna",
      "Jessore",
      "Satkhira",
      "Bagerhat",
      "Narail",
      "Magura",
      "Kushtia",
      "Chuadanga",
      "Meherpur",
      "Jhenaidah",
    ],
    "Barisal": [
      "Barisal",
      "Patuakhali",
      "Bhola",
      "Pirojpur",
      "Barguna",
      "Jhalokathi",
    ],
    "Sylhet": ["Sylhet", "Moulvibazar", "Habiganj", "Sunamganj"],
    "Rangpur": [
      "Rangpur",
      "Dinajpur",
      "Gaibandha",
      "Kurigram",
      "Lalmonirhat",
      "Nilphamari",
      "Panchagarh",
      "Thakurgaon",
    ],
    "Mymensingh": ["Mymensingh", "Jamalpur", "Sherpur", "Netrokona"],
  };
}
