# New Feature Development Workflow

name: "New Feature Development Workflow"
version: "1.0.0"

trigger: "নতুন feature add করতে হলে"

steps:
  - name: "1. Requirements Analysis"
    actions:
      - "Feature requirements clearly বোঝো"
      - "API endpoints identify করো"
      - "UI/UX design review করো"
      - "Edge cases list করো"

  - name: "2. Data Layer"
    depends_on: ["1"]
    actions:
      - "Model create করো with fromJson/toJson"
      - "Repository implement করো"
    files:
      - "lib/data/models/{feature}_model.dart"
      - "lib/features/{feature}/data/{feature}_repository.dart"

  - name: "3. Feature Layer"
    depends_on: ["2"]
    actions:
      - "Provider/Controller create করো"
      - "State class define করো (with Freezed)"
    files:
      - "lib/features/{feature}/controllers/{feature}_controller.dart"
      - "lib/features/{feature}/providers/{feature}_provider.dart"

  - name: "4. Presentation Layer"
    depends_on: ["3"]
    actions:
      - "Screen create করো"
      - "Widgets create করো"
    files:
      - "lib/presentation/{feature}/{feature}_screen.dart"
      - "lib/presentation/{feature}/widgets/"

  - name: "5. Integration"
    depends_on: ["4"]
    actions:
      - "Route add করো (lib/navigation/app_router.dart)"
      - "Navigation implement করো"

  - name: "6. Testing"
    depends_on: ["5"]
    actions:
      - "Unit tests লেখো"
      - "Widget tests লেখো"
    files:
      - "test/unit/{feature}/"
      - "test/widget/{feature}/"

  - name: "7. Code Generation"
    actions:
      - "Run: flutter pub run build_runner build --delete-conflicting-outputs"

example_prompt: |
  আমি "Reviews" feature add করতে চাই। Users product এ review দিতে পারবে।

  API Endpoints:
  - GET /api/products/:id/reviews - Get product reviews
  - POST /api/products/:id/reviews - Add review

  এই feature এর জন্য সব layers implement করো।
